server:
  port: 8091
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123123
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    hibernate:
      ddl-auto: update